`
PROP

-> PROP IS ONE TYPE OF PARAMETERE WHICH IS USED TO GET/SEND DATA FROM/TO ANOTHRE COMPONENT.

-> PROCESS OF PASSING DATA FROM ONE COMPONENT TO ANOTHER COMPONENT CALLED PROP PASSING.

-> IF PROP PASSING IS NESTED THEN ITS CALLED PROP DRILLING.

-> IF WE WANT USE STATE OF A COMPONENT INTO ANOTHER COMPONENT.

   - SECOND COMPONENT MUST BE CHILD OF FIRST COMPONENT

   - PROP PASSING PARENT TO CHILD - A -> B -> C -> D NOTE- (YOU CANT PASS PROP CHILD TO PARENT COMPONENT).

-> SCREEN - 

`
